#!/usr/bin/env bash

## TODO: move siri settings into separate script

## get sudo status
if [[ "$EUID" = 0 ]]; then
        SUDOER=true
else
        echo "Skipping preferneces that require sudo. Re-run with sudo to enable"
fi


## launch chrome and make it the default broswer
open -a "Google Chrome" --args --make-default-browser
pkill -a -i "Google Chrome"


## dock and spaces
defaults delete com.apple.dock && killall Dock    # reset defaults
defaults write com.apple.dock autohide -bool false   # disable autohide
defaults write com.apple.dock dashboard-in-overlay -bool true   # don't show dashboard as space
defaults write com.apple.dashboard mcx-disabled -boolean YES    # disable dashboard
defaults write com.apple.dock mru-spaces -bool false    # do not automatically rearrange spaces on recent use
killall Dock    # restart dock


## firewall
if [[ $SUDOER ]]; then
        sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate on    # enable firewall
        sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setallowsigned   # allow signed built-in applications automatically
        sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setstealthmode on    # enable stealth mode
        sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setloggingmode on    # enable log mode
        sudo pkill -HUP socketfilterfw  # apply changes
fi

## security
defaults write com.apple.screensaver askForPassword -int 1  # ask for password on screensaver
defaults write com.apple.screensaver askForPasswordDelay -int 0 # no delay on password for screensaver
if [[ $SUDOER ]]; then
        sudo spctl --master-enable  # enable gatekeeper
        sudo defaults write /Library/Preferences/com.apple.loginwindow GuestEnabled -bool false # disable guest account
fi

## auto updates
defaults write com.apple.SoftwareUpdate AutomaticCheckEnabled -bool true     # check for updates automatically
defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1    # check for updates daily
defaults write com.apple.SoftwareUpdate AutomaticDownload -int 1    # auto-download updates
defaults write com.apple.SoftwareUpdate CriticalUpdateInstall -int 1    # auto-install updates


## finder
defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true  # show external drives on desktop 
defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true  # show removeable media on desktop
defaults write com.apple.finder DisableAllAnimations -bool true # disable window animations and Get Info animations
defaults write com.apple.finder ShowPathbar -bool true  # show path in finder window
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false  # disable warning when changing a file extension
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true    # no .DS files on network drives
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true    # no .DS files on usb drives
defaults write com.apple.finder EmptyTrashSecurely -bool true   # secure trash empty by default
defaults write NSGlobalDomain AppleShowAllExtensions -bool true # show all filename extensions
killall Finder  # restart finder


## spotlight
defaults write com.apple.spotlight orderedItems -array \
        '{"enabled" = 1;"name" = "APPLICATIONS";}' \
        '{"enabled" = 1;"name" = "SYSTEM_PREFS";}' \
        '{"enabled" = 1;"name" = "DIRECTORIES";}' \
        '{"enabled" = 0;"name" = "PDF";}' \
        '{"enabled" = 0;"name" = "FONTS";}' \
        '{"enabled" = 0;"name" = "DOCUMENTS";}' \
        '{"enabled" = 0;"name" = "MESSAGES";}' \
        '{"enabled" = 1;"name" = "CONTACT";}' \
        '{"enabled" = 0;"name" = "EVENT_TODO";}' \
        '{"enabled" = 0;"name" = "IMAGES";}' \
        '{"enabled" = 0;"name" = "BOOKMARKS";}' \
        '{"enabled" = 0;"name" = "MUSIC";}' \
        '{"enabled" = 0;"name" = "MOVIES";}' \
        '{"enabled" = 0;"name" = "PRESENTATIONS";}' \
        '{"enabled" = 0;"name" = "SPREADSHEETS";}' \
        '{"enabled" = 0;"name" = "SOURCE";}' \
        '{"enabled" = 0;"name" = "MENU_DEFINITION";}' \
        '{"enabled" = 0;"name" = "MENU_OTHER";}' \
        '{"enabled" = 0;"name" = "MENU_CONVERSION";}' \
        '{"enabled" = 0;"name" = "MENU_EXPRESSION";}' \
        '{"enabled" = 0;"name" = "MENU_WEBSEARCH";}' \
        '{"enabled" = 0;"name" = "MENU_SPOTLIGHT_SUGGESTIONS";}'

killall mds > /dev/null 2>&1    # Load new settings before rebuilding the index
if [[ $SUDOER ]]; then
        sudo mdutil -E / > /dev/null    # Rebuild the index from scratch
fi


## disable siri
defaults write com.apple.Siri StatusMenuVisible -bool false
defaults write com.apple.Siri UserHasDeclinedEnable -bool true
defaults write com.apple.assistant.support 'Assistant Enabled' 0
# clear and lock siri analytics database which is created even if the siri launch agent disabled
rm -rfv ~/Library/Assistant/SiriAnalytics.db
chmod -R 000 ~/Library/Assistant/SiriAnalytics.db
chflags -R uchg ~/Library/Assistant/SiriAnalytics.db


## menu bar
defaults write com.apple.menuextra.clock IsAnalog -bool false   # view clock as digital
defaults write com.apple.menuextra.clock FlashDateSeparators -bool false    # no flashing
defaults write com.apple.menuextra.clock DateFormat -string "EEE MMM d  h:mm a" # set date string like "Thu Dec 13  1:45 AM"
defaults write com.apple.menuextra.battery ShowPercent -bool true   # show battery percentage
defaults write com.apple.airplay showInMenuBarIfPresent -bool true      # show airplay options when available
defaults write com.apple.systemuiserver menuExtras -array \
        "/System/Library/CoreServices/Menu Extras/TimeMachine.menu" \
        "/System/Library/CoreServices/Menu Extras/AirPort.menu" \
        "/System/Library/CoreServices/Menu Extras/Battery.menu" \
        "/System/Library/CoreServices/Menu Extras/Clock.menu" \
        "/System/Library/CoreServices/Menu Extras/Bluetooth.menu" \
        "/System/Library/CoreServices/Menu Extras/User.menu" \
        "/System/Library/CoreServices/Menu Extras/Displays.menu"


## NSGlobalDomain settings

# Disable automatic capitalization as it’s annoying when typing code
defaults write NSGlobalDomain NSAutomaticCapitalizationEnabled -bool false

# Disable smart dashes as they’re annoying when typing code
defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false

# Disable automatic period substitution as it’s annoying when typing code
defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool false

# Disable smart quotes as they’re annoying when typing code
defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false

# Alway show scroll bars
defaults write NSGlobalDomain AppleShowScrollBars -string "Always"


## other

# Use plain text mode for new TextEdit documents
defaults write com.apple.TextEdit RichText -int 0

# Enable Secure Keyboard Entry in Terminal.app
defaults write com.apple.terminal SecureKeyboardEntry -bool true

# Save to disk (not to iCloud) by default
defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false

## other-  sudo required
if [[ $SUDOER ]]; then
        # disable captive portal
        sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.captive.control Active -bool false

        ## apply changes
        sudo killall -HUP cfprefsd && killall SystemUIServer
fi