#!/usr/bin/env bash

# get list of terminal theme files in dir
match="*.terminal"  
themes=( $match )   # build array

if [ ${#themes[@]} -gt 1 ]; then
    echo "info: multiple custom terminal theme files discovered"
    echo "info: using ${themes[0]}"
fi

# open first terminal theme in order to import theme. close after
# TODO: find a way to install theme without opening
open ${themes[0]}
sleep 5 # wait to ensure terminal has time to open and install theme

# set defaults
basename=${themes[0]%.*}  # cuts string at "."
defaults write $HOME/Library/Preferences/com.apple.Terminal.plist "Default Window Settings" "${basename}"
defaults write $HOME/Library/Preferences/com.apple.Terminal.plist "Startup Window Settings" "${basename}"
